name: Optimize resource pack
on:
  push:
    tags:
      - '**'
permissions:
    contents: write
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/ExitiumPack.zip'

            ['**/*?.md']
            force_include = true
      - name: Generate_SHA1
        run: |
          pack_sha1=$(sha1sum /tmp/ExitiumPack.zip | awk '{ print $1 }')
          echo "PACK_SHA1=$pack_sha1" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/ExitiumPack.zip
          body: "SHA1: `${{ steps.Generate_SHA1.outputs.PACK_SHA1 }}`"